### ISSUE TITLE
Provide integration with Alexa

### ISSUE THREAD

**Issue by CosminNechifor** [biabeniamin/DatabaseFunctionsGenerator#1]
## Problem definition

The overall concept is really good but it would be even better to add integration with the Alexa module you've developed. Then in my opinion this will become a beast if you know where and when to use it.

**Comment by biabeniamin** [comment]
The application generates the models and methods to get data. Add methods still have to be implemented.

**Comment by biabeniamin** [comment]
The add method was implemented.
